from collections.abc import Callable
from typing import TypeVar

from typer import main as main

CommandFunction = TypeVar("CommandFunction", bound=Callable[..., object])

class OptionInfo: ...
class ArgumentInfo: ...
class TyperException(Exception): ...

class BadParameter(TyperException):
    def __init__(self, message: str) -> None: ...

class Typer:
    def __init__(
        self, *, add_completion: bool = ..., no_args_is_help: bool = ..., help: str | None = ...
    ) -> None: ...
    def command(self) -> Callable[[CommandFunction], CommandFunction]: ...

def Option(*param_decls: str, case_sensitive: bool = ...) -> OptionInfo: ...
def Argument(*, case_sensitive: bool = ...) -> ArgumentInfo: ...
def echo(message: str, *, err: bool = ...) -> None: ...
