import numpy as np
from numpy.typing import NDArray

class PCA:
    def __init__(self, n_components: float, svd_solver: str, random_state: int) -> None: ...
    def fit(self, features: NDArray[np.float64]) -> PCA: ...
    def transform(self, features: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def inverse_transform(self, features: NDArray[np.float64]) -> NDArray[np.float64]: ...
