import numpy as np
from numpy.typing import NDArray

class LocalOutlierFactor:
    def __init__(self, n_neighbors: int, novelty: bool, n_jobs: int) -> None: ...
    def fit(self, features: NDArray[np.float64]) -> LocalOutlierFactor: ...
    def score_samples(self, features: NDArray[np.float64]) -> NDArray[np.float64]: ...
    def kneighbors(
        self, features: NDArray[np.float64], n_neighbors: int
    ) -> tuple[NDArray[np.float64], NDArray[np.int64]]: ...
