import numpy as np
from numpy.typing import NDArray

class IsolationForest:
    def __init__(self, n_estimators: int, random_state: int, n_jobs: int) -> None: ...
    def fit(self, features: NDArray[np.float64]) -> IsolationForest: ...
    def score_samples(self, features: NDArray[np.float64]) -> NDArray[np.float64]: ...
