from collections.abc import Sequence
from typing import Any

import numpy as np
from matplotlib.artist import Artist
from numpy.typing import NDArray

Data = Sequence[float] | NDArray[np.number[Any]] | float
Labels = Sequence[str]
Errors = Sequence[Sequence[float]] | NDArray[np.number[Any]] | float | None

class Axes:
    def set_title(self, label: str) -> None: ...
    def set_xlabel(self, label: str) -> None: ...
    def set_ylabel(self, label: str) -> None: ...
    def set_xscale(self, value: str) -> None: ...
    def set_yscale(self, value: str) -> None: ...
    def set_xticks(self, ticks: Data, labels: Labels | None = None, **kwargs: object) -> None: ...
    def set_yticks(self, ticks: Data, labels: Labels | None = None, **kwargs: object) -> None: ...
    def grid(self, **kwargs: object) -> None: ...
    def plot(self, x: Data, y: Data, **kwargs: object) -> list[Artist]: ...
    def step(self, x: Data, y: Data, **kwargs: object) -> list[Artist]: ...
    def scatter(self, x: Data, y: Data, **kwargs: object) -> Artist: ...
    def errorbar(
        self, x: Data, y: Data, xerr: Errors = None, yerr: Errors = None, **kwargs: object
    ) -> Artist: ...
    def bar(self, x: Data, height: Data, **kwargs: object) -> Artist: ...
    def barh(self, y: Data, width: Data, **kwargs: object) -> Artist: ...
    def fill_between(self, x: Data, y1: Data, y2: Data, **kwargs: object) -> Artist: ...
    def axhline(self, y: float, **kwargs: object) -> Artist: ...
    def axvline(self, x: float, **kwargs: object) -> Artist: ...
    def legend(self, *args: object, **kwargs: object) -> Artist: ...
    def get_legend_handles_labels(self) -> tuple[list[Artist], list[str]]: ...
